### ISSUE TITLE
Provide a way to run a specific set of test(s)

### ISSUE THREAD

**Issue by MichaelAquilina** [zunit-zsh/zunit#86]
If you are trying to debug a single test case amongst a bunch of other tests, this is extremely useful

**Comment by molovo** [comment]
This is difficult, because of the way ZUnit has to parse files. You can run individual tests (See 'Running Individual Tests' section [on this page](https://zunit.xyz/docs/usage/running-tests/)). The only other thing i can suggest at the moment is subfoldering groups of tests and passing the subfolder path to zunit.

It might be possible to tweak the way individual tests are run to accept wildcards so that you can namespace tests with a name like `namespace:test name`. I can look into that if it'll help

**Comment by MichaelAquilina** [comment]
This is me actually failing to read the documentation correctly so I think we can close this :)
